<?php

declare(strict_types=1);

namespace ContaAzulCli\Auth;

use ContaAzulCli\Config\Configuration;

/** Backwards-compatible facade over token access and interactive login services. */
final class AuthManager
{
  private readonly AccessTokenServiceInterface $accessTokens;
  private readonly LoginService $login;

  /**
   * Creates the authentication facade.
   *
   * The optional services let the composition root provide alternate
   * implementations while the original three-argument constructor remains
   * source-compatible with existing integrations.
   *
   * @param TokenRepositoryInterface         $tokenStore   Local token persistence.
   * @param OAuthGatewayInterface            $oauthClient  OAuth provider adapter.
   * @param Configuration                    $config       Runtime configuration.
   * @param AccessTokenServiceInterface|null $accessTokens Optional token service.
   * @param LoginService|null                $login        Optional browser-login service.
   */
  public function __construct(
      TokenRepositoryInterface $tokenStore,
      OAuthGatewayInterface $oauthClient,
      Configuration $config,
      AccessTokenServiceInterface|null $accessTokens = null,
      LoginService|null $login = null,
  ) {
    $this->accessTokens = $accessTokens ?? new AccessTokenService(
        $tokenStore,
        $oauthClient,
        $config,
        new FileTokenLock($tokenStore->getPath()),
    );
    $this->login        = $login ?? new LoginService($oauthClient, $tokenStore, $config);
  }

  /** Returns a valid access token, refreshing it when necessary. */
  public function getValidAccessToken(): string
  {
    return $this->accessTokens->getValidAccessToken();
  }

  /** Refreshes the access token after an API request receives HTTP 401. */
  public function refreshAfter401(): string
  {
    return $this->accessTokens->refreshAfter401();
  }

  /** Starts browser authentication and returns its authorization URL. */
  public function startLoginFlow(): string
  {
    return $this->login->start();
  }

  /** Returns the pending CSRF state generated by the login flow. */
  public function getPendingState(): string|null
  {
    return $this->login->pendingState();
  }

  /** Completes browser authentication and persists the exchanged token. */
  public function completeLoginFlow(string $code): void
  {
    $this->login->complete($code);
  }

  /** Removes locally cached credentials. */
  public function logout(): void
  {
    $this->accessTokens->logout();
  }
}
