<?php

declare(strict_types=1);

namespace ContaAzulCli\Auth;

use ContaAzulCli\Config\Configuration;
use Ramsey\Uuid\Uuid;

use function array_filter;
use function http_build_query;
use function str_contains;

/** Coordinates the browser-based OAuth authorization-code login flow. */
final class LoginService
{
  private string|null $pendingState = null;

  /**
   * @param OAuthGatewayInterface    $oauthGateway    OAuth code exchange adapter.
   * @param TokenRepositoryInterface $tokenRepository Local token persistence.
   * @param Configuration            $config          Runtime OAuth endpoint configuration.
   */
  public function __construct(
      private readonly OAuthGatewayInterface $oauthGateway,
      private readonly TokenRepositoryInterface $tokenRepository,
      private readonly Configuration $config,
  ) {
  }

  /** Builds an authorization URL and remembers its CSRF state value. */
  public function start(): string {
    $this->pendingState = Uuid::uuid4()->toString();

    $params = array_filter(
        [
          'response_type' => 'code',
          'client_id'     => $this->config->clientId,
          'redirect_uri'  => $this->config->redirectUri,
          'scope'         => $this->config->scope,
          'state'         => $this->pendingState,
        ],
    );

    // Fragment routes need the query appended after the fragment itself.
    $separator = str_contains($this->config->authorizeUrl, '?') ? '&' : '?';

    return $this->config->authorizeUrl . $separator . http_build_query($params);
  }

  /** Returns the state generated by the most recent login start, if any. */
  public function pendingState(): string|null {
    return $this->pendingState;
  }

  /** Exchanges a callback code, persists the token, and clears pending state. */
  public function complete(string $code): void {
    $token = $this->oauthGateway->exchangeCode($code);
    $this->tokenRepository->save($token);
    $this->pendingState = null;
  }
}
