<?php

declare(strict_types=1);

namespace ContaAzulCli\Auth;

use ContaAzulCli\Config\Configuration;
use Ramsey\Uuid\Uuid;

/** Coordinates the browser-based OAuth authorization-code login flow. */
final class LoginService
{
  private ?string $pendingState = NULL;


  /**
   * @param OAuthGatewayInterface $oauthGateway OAuth code exchange adapter.
   * @param TokenRepositoryInterface $tokenRepository Local token persistence.
   * @param Configuration $config Runtime OAuth endpoint configuration.
   */
  public function __construct(
        private readonly OAuthGatewayInterface $oauthGateway,
        private readonly TokenRepositoryInterface $tokenRepository,
        private readonly Configuration $config,
    ) {
  }


  /** Builds an authorization URL and remembers its CSRF state value. */
  public function start(): string {
    $this->pendingState = Uuid::uuid4()->toString();

    $params = array_filter(
      [
        'response_type' => 'code',
        'client_id'     => $this->config->getClientId(),
        'redirect_uri'  => $this->config->getRedirectUri(),
        'scope'         => $this->config->getScope(),
        'state'         => $this->pendingState,
      ]
    );

    // Fragment routes need the query appended after the fragment itself.
    $separator = str_contains($this->config->getAuthorizeUrl(), '?') ? '&' : '?';

    return $this->config->getAuthorizeUrl() . $separator . http_build_query($params);
  }


  /** Returns the state generated by the most recent login start, if any. */
  public function pendingState(): ?string {
    return $this->pendingState;
  }


  /** Exchanges a callback code, persists the token, and clears pending state. */
  public function complete(string $code): void {
    $token = $this->oauthGateway->exchangeCode($code);
    $this->tokenRepository->save($token);
    $this->pendingState = NULL;
  }


}
